name: CI
on:
  push:
  workflow_dispatch:

# taken from https://github.com/kubernetes-sigs/kind/blob/v0.25.0/.github/workflows/vm.yaml#L47-L84
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LIMA_VERSION: "1.0.7"
    steps:
      - uses: actions/checkout@v4

      - name: "Install QEMU"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ovmf qemu-system-x86 qemu-utils
          sudo modprobe kvm
          # `sudo usermod -aG kvm $(whoami)` does not take an effect on GHA
          sudo chown $(whoami) /dev/kvm

      - name: "Install Lima"
        run: curl -fsSL https://github.com/lima-vm/lima/releases/download/v${LIMA_VERSION}/lima-${LIMA_VERSION}-Linux-x86_64.tar.gz | sudo tar Cxzvf /usr/local -

      - name: "Cache ~/.cache/lima"
        uses: actions/cache@v4
        with:
          path: ~/.cache/lima
          key: lima-${{ env.LIMA_VERSION }}

      - name: "Start Fedora"
        # --plain is set to disable file sharing, port forwarding, built-in containerd, etc.
        run: limactl start --name=default --plain template://fedora

      - name: "Initialize Fedora"
        # plain old rsync and ssh are used for the initialization of the guest,
        # so that people who are not familiar with Lima can understand the initialization steps.
        run: |
          set -eux -o pipefail
          # Initialize SSH
          mkdir -p -m 0700 ~/.ssh
          cat ~/.lima/default/ssh.config >> ~/.ssh/config
          # Sync the current directory to /tmp/kind in the guest
          rsync -a -e ssh . lima-default:/tmp/kind
          # Install packages
          # Enable systemd lingering for rootless
          ssh lima-default sudo loginctl enable-linger "$USER"
          # Install kind
          ssh lima-default uname -a
